Brewery.delete_all
Beer.delete_all

alechemy = Brewery.create!({name: "Alechemy", lat: 55.863904, lng: -3.535432, description: "If you are a lover of hand-crafted real ales, then you should check out Alechemy Brewing. Our Edinburgh brewery is a small family run business that aims to provide a true alternative to the proliferation of mass produced and marketed beers. As an independent brewer, we are free to create a range of occasional speciality beers that compliment our core range of bottled and cask ales. We produce beers of all styles, so there is bound to be something in our range to please even the most experienced connoisseur. ", image: "http://res.cloudinary.com/ratebeer/image/upload/w_400,c_limit/brew_14372.jpg"})
arran = Brewery.create!({name: "Isle of Arran Brewery", lat: 55.496573, lng: -5.093847, description: "Situated just off the West coast of Scotland the Isle of Arran is arguably one of the most beautiful and dramatic islands in Europe. The splendour and diversity of the landscape has led it to be considered by many as Scotland in miniature. Nestled between the islands largest mountain, Goatfell and the imposing Brodick Castle lies Arran Brewery which has been brewing award winning craft beer for over a decade.", image: "https://www.bottle-shop.co.uk/media/catalog/category/arran.jpg"})
barneys = Brewery.create!({name: "Barney's Beer", lat: 55.93983, lng: -3.182257, description: "The son of a brewery worker in the Midlands, Barney got his first taste of  brewery & maltings work aged 16. A degree in Brewing & Distilling Science drew him to Edinburgh and number of positions in brewing & distilling followed; including time at the Fountainbridge Brewery, Edinburgh, Brugal Rum and The Macallan. Barney’s Beer was founded in 2010, moving to Summerhall in 2012. In December 2013 Barney’s Beer was declared one of the top 5 craft brewers in Scotland by The List magazine & in 2014 Red Rye was honored with a gold award by SIBA Scotland (Volcano IPA picked up a silver). The regular beer line-up is Good Ordinary Pale Ale, Red Rye, Volcano IPA & Extra Pale.", image: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/68541f21551287.563054a2f26f1.jpg"})
belhaven = Brewery.create!({name: "Belhaven ", lat: 55.993417, lng: -2.509047, description: "Belhaven – or “Beautiful harbour” – nestles among the rolling barley fields of the beautiful East Lothian coast, around 20 miles east of Edinburgh. For nearly 300 years, we have brewed in this place using only the finest local barley and choicest hops. Established in 1719, Belhaven is Scotland’s oldest working brewery. With abundant local barley, fine water from the brewery well and access to markets up and down the coast, Belhaven was the perfect place for a brewery back then, and it still is today.", image: "http://files.the-group.net/library/GreeneKing/zips/dw_18.jpg"})
black_isle = Brewery.create!({name: "Black Isle Organic", lat: 57.534224, lng: -4.295452, description: "Black Isle was started by David Gladwin in 1998. An unemployed beer lover, he set out to make world class beer using barley and hops grown on organic farms as nature intended, without the use of destructive chemicals. Today we can brew up to 10,000 litres a day packaged in bottles, casks and kegs. We ship beer all over Scotland, the UK and around the world from Sweden to Japan.", image: "http://www.stroudbrewery.co.uk/festival/wp-content/uploads/2016/04/Black-Isle-Organic.jpeg"})
brewdog = Brewery.create!({name: "Brewdog", lat: 57.371609, lng: -2.048336, description: "At brewdog we are on a mission to make other people as passionate about great craft beer as we are. All we care about is brewing world class craft beer; extraordinary beers that blow people's minds and kick start a revolution.", image: "https://upload.wikimedia.org/wikipedia/en/6/66/Large_brewdog-logo.gif"})
broughton_ales = Brewery.create!({name: "Brougton Ales", lat: 55.610294, lng: -3.413646, description: "Broughton Ales is a brewery in Broughton, in the Scottish Borders. The brewery was founded in 1979 by David Younger and James Collins in Broughton village and was the first initiated Scottish microbrewery. Broughton produces traditional cask conditioned beer, bottled beer and keg beer.", image: "https://www.visitscotland.com/wsimgs/Broughton%20Ales%20main%20image_1419091061.jpg"})
cairngorm = Brewery.create!({name: "Cairngorm", lat: 57.200876, lng: -3.820506, description: "The Cairngorm Brewery Company, established in 2001, is situated in the village of Aviemore within the Cairngorms National Park in the Highlands of Scotland. We brew traditional ales with a fresh new edge, by using well established brewing methods, the finest malted and roast barley, hops and crystal clear mountain water.", image: "http://www.whatalesyou.co.uk/ugc/brewery/Cairngorm/cairngorm%20brewery%201.jpg"})
caledonian = Brewery.create!({name: "Caledonian Brewery", lat: 55.935539, lng: -3.231001, description: "Brewed in EdinburghCaledonian Brewery has been part of Edinburgh's life for a long time. Well over 140 years, in fact. Time enough for both of us to develop an appreciation of each other's special character.", image: "http://www.gullivertaverns.co.uk/Breweries/Scotland_Breweries/Caledonian/Caledonian_logo.jpg"})
fyne_ales = Brewery.create!({name: "Fyne Ales", lat: 56.276006, lng: -4.912004, description: "At Fyne Ales we are all about producing an outstanding range of modern British beers, which we make in a spectacular location, and with integrity in everything we do. Our beers are built on the British Cask Ale tradition, Britain’s contribution to the global beer culture. This is a method that allows us to pack large amounts of flavour into relatively low alcohol beers. To this we have added a focus on new beer styles and big flavoured hops from the New World. This enables us to produce bold hop-forward beers that retain balance and subtlety.", image: "http://www.helensburghalefest.co.uk/wp-content/uploads/2016/04/fyne-500.png"})
harviestoun = Brewery.create!({name: "Harviestoun", lat: 56.14984, lng: -3.786828, description: "For 30 years we've been experimenting, mixing, juxtaposing, playing with world famous whisky casks, chasing after aftertastes; and exploring the many possibilities of our craft. Here's to fun!", image: "https://whisk-e.co.jp/wp-content/uploads/2015/08/Harviestoun_logo.jpg"})
innisgunn = Brewery.create!({name: "Innis & Gunn", lat: 55.951969, lng: -3.210914, description: "We’re a little brewer, and a little unusual. We mature our beer with oak, producing unique flavours and a range of beers that are finding friends around the world (touch wood).", image: "http://beeralien.com/wp-content/uploads/2014/04/innis_gunn_logo.jpg"})
inveralmond = Brewery.create!({name: "Inveralmond Brewery", lat: 56.417762, lng: -3.471942, description: "Enjoyability. It’s that simple ingredient that brings you back, time and again, to the beer you love, and, at Inveralmond Brewery, we have over a century’s experience in the brewing of it. From Scottish legends like Ossian and Lia Fail, to our intrepid new Inspiration Series, we’re in the business of crafting deliciousness, meaning each and every pint tastes as brilliant as the last. ", image: "http://www.inveralmond-brewery.co.uk/img/logo.png"})
kelburn = Brewery.create!({name: "Kelburn Brewing Company", lat: 55.804442, lng: -4.392248, description: "We are a family-run, traditional brewery with our main focus being on quality, not quantity. As consumers, the team at Kelburn like to drink beers of a high standard and so equally, as suppliers, we aim to produce the very same thing.", image: "http://www.scottishbrewing.com/breweries/glasgowandwest/img/kelburn-brewing-logo.png"})
knops = Brewery.create!({name: "Knops Beer", lat: 56.044926, lng: -2.802621, description: "Knops Beer Company was born out of a desire to explore the rich heritage and variety that beer has to offer and to brew beers that can appeal to all levels, from the experienced ale drinker to those who have never been lucky enough to discover the range and depth of this vibrant category.", image: "http://www.scottishbrewing.com/breweries/edinburghandlothians/img/knops-logo.png"})
loch_lomand = Brewery.create!({name: "Loch Lomand", lat: 55.994271, lng: -4.575934, description: "The natural phenomena which is Loch Lomond is at the heart of everything the brewery stands for and is the driving force behind the breweries creation and success. The outstanding natural beauty of the Loch and its surrounding area has inspired and captivated people for centuries and we are no different.  ", image: "http://www.scottishbrewing.com/breweries/glasgowandwest/img/loch-lomond-brewery-logo-black.png"})
orkney = Brewery.create!({name: "Orkney Brewery", lat: 59.069236, lng: -3.309611, description: "The tranquil Orkney Islands, with their fertile farming lands and fishing grounds, have been inhabited for over 5000 years. The Orkney brewery is housed in the former schoolhouse in Quoyloo one mile from Skara Brae in the heart of Neolithic Orkney.", image: "http://www.scottishbrewing.com/breweries/orkneyandshetland/img/orkney-brewery-logo.png"})
old_worthy = Brewery.create!({name: "Old Worthy", lat: 55.953495, lng: -3.209392, description: "Old men in Scottish pubs have been drinking their ales with a dram since forever. It’s called a Half ‘n Half. It’s what you do in Scotland. At Old Worthy Brewing Co, we love a Half ‘n Half, that special marriage of whisky and beer. Let’s just say, delicious.It’s why we brew our beers. Every single one of them. We source our malt from Scotland’s famous whisky distilleries and brew up some mischief. Ales that do justice to the drams we love.", image: "http://www.oldworthybeer.co.uk/wp-content/uploads/2015/07/logoset-new.png"})
st_andrews = Brewery.create!({name: "St Andrews Brewing", lat: 56.338921, lng: -2.799243, description: "St Andrews Brewing Company,  a locally owned Scottish brewery, producing craft beer in Fife. We serve kegged, casked and bottled conditioned real ale at our brewpub, which is developing a reputation as one of the must visit bars in Scotland.", image: "http://www.scotlandsspecialityfoodshow.com/sites/default/files/exhibitor_images/Main%20Logo.jpg"})
skye = Brewery.create!({name: "Isle of Skye Brewing", lat: 57.586777, lng: -6.377714, description: "From rain-soaked soil to the glass in your hand, we use only the most authentic ingredients in our ales. That even means milling our own grains – right here at the brewery. This gives us complete control over flavour and freshness. And when an ale calls for a little extra bitterness, we simply hand-pick local berries and plants. All to let the true taste of malt shine through.", image: "https://pbs.twimg.com/profile_images/462266719910633472/hGbsV79Y.jpeg"})
stewart = Brewery.create!({name: "Stewart Brewing", lat: 55.872579, lng: -3.161443, description: "Stewart Brewing, founded in 2004 by Steve and Jo Stewart, is Edinburgh's local, independent brewery. Our business is based on two very basic principles.To produce beers of the highest quality possible and to provide an exceptional service to its customers.", image: "https://pbs.twimg.com/profile_images/593772972776759296/4S028b3-.jpg"})
strathaven = Brewery.create!({name: "Strathaven Ales", lat: 55.674873, lng: -4.023977, description: "Strathaven Ales is the pinnacle of traditional real ale brewing with our stone clad brewing kettle and well used brew-house based in an old mill dating back to the early 1800s. The mill originally manufactured crushed barley for the brewery trade and flour for the local artisan bakers and it sits next to the river Avon near the market town of Strathaven. ", image: "http://www.scottishbrewing.com/breweries/glasgowandwest/img/strathaven-ales-logo.png"})
tempest = Brewery.create!({name: "Tempest Brewing Co", lat: 55.602243, lng: -2.75733, description: "We brew our beer taking inspiration from our history as a brewery; from the hops we found in New Zealand, to our local produce in Scotland. Tempest was born and forged from the passion, creativity, and drive that Gavin and Annika had for wanting to start a brewery. Their adventure from start to present is there in every bottle of beer we make. Every beer tells a story, whether it’s Long White Cloud being brewed for the first time in a garage in Christchuch, to Unforgiven brewed as the answer to the question “what would a cowboy drink?”.", image: "http://www.scottishbrewing.com/breweries/scottishborders/img/tempest-brewing-logo.png"})
williams_bros = Brewery.create!({name: "Williams Bros", lat: 56.112451, lng: -3.813504, description: "Williams Bros. Brewing Co. is located in Alloa, Clackmannanshire and is set in the old George Younger’s bottling hall in Kelliebank. Although now producing an eclectic range of Craft Beers for the international market, the Brotherhood 'Brew House' is steeped in Scottish tradition and remains the last bastion of brewing in a town, which was once regarded as 'Scotland's Beer Capital'.", image: "http://beerguild.co.uk/wp-content/uploads/2012/01/WB-Logo-2011-White.jpg"})


# Alechemy
Beer.create!({name: "Ritual Pale Ale", avb: "4.1%", description: "Our flagship beer. Ritual is an IPA with a medium malt backbone giving way to refreshing bitterness, with a citrus and slightly spicy hop aroma.", brewery_id: alechemy.id})
Beer.create!({name: "Citra Burst IPA", avb: "5.4%", description: "Does exactly what it says on the….. well pump clip. An easy drinking favourite among many, Citra Burst is a light golden India pale ale with resinous pine and citrus flavours and light aroma of citrus zest.", brewery_id: alechemy.id})
Beer.create!({name: "Bad Day At The Office Ale", avb: "4.5%", description: "An accolade to a long and frustrating day. With a generous amount of hops and a low ABV, what better way to put a smile back on your face? A light golden ale with a heavy hop bitterness and flavoured with a strong fruit and citrus aroma", brewery_id: alechemy.id})
Beer.create!({name: "Rye O' Rye Red Rye Pale", avb: "5.6%", description: "A deep flavoured amber ale with a complex rye spice. Fruity hops helping balance the rye to give a warming and pleasant finish.", brewery_id: alechemy.id})
Beer.create!({name: "Sterotype Steam Lager", avb: "4.5%", description: "The best inventions were created by accident, up there with Penicillin and Viagra is Alechemy’s first bottled Lager, Stereotype. This, however, is not your stereotypical lager. This is a full flavoured lager with a spicy hoppy taste and a clean bitter dryness.", brewery_id: alechemy.id})

# arran
Beer.create!({name: "Red Squirrel", avb: "3.8%", description: "Chestnut red session ale with a nutty aroma, toasted caramel hints and a deep malty palate. ", brewery_id: arran.id})
Beer.create!({name: "Red Milestone", avb: "6%", description: "Milestone was produced to mark the 1000th brew on Arran. Bottle conditioned beer was chosen due to the increasing demand for the excellent characteristics and flavour produced by having beer with live yeast in the bottle.. ", brewery_id: arran.id})
Beer.create!({name: "Fireside", avb: "4.7%", description: "Chestnut red session ale with a nutty aroma, toasted caramel hints and a deep malty palate. ", brewery_id: arran.id})
Beer.create!({name: "Red Squirrel", avb: "3.8%", description: "Smooth dark amber malty brew with a warm ginger aroma and a sweet bitter & spicy finish., the perfect beer for the cold winter nights.", brewery_id: arran.id})
Beer.create!({name: "Sleeping Warrior", avb: "8.3%", description: "Barley Wine is a style of strong ale originating in England and was normally kept for the aristocracy. The use of the word wine is due to its similar alcoholic strength of a fine wine, However since it is made from grain rather than fruit it is in fact, a Beer! ", brewery_id: arran.id})
Beer.create!({name: "clyde puffer", avb: "4.5%", description: "Named after the small boats which served the islands of the Clyde, Clyde Puffer is an oatmeal stout with a coffee and nut aroma. Sweet and mellow body with a low hop taste, hints of coffee and dark chocolate and a smooth silky finish.", brewery_id: arran.id})
Beer.create!({name: "Sunset", avb: "4.4%", description: "Isle of Arran Sunset Premium beer brings together a unique balance of nature and freshness only rarely found. Isle of Arran Sunset delivers a mature taste of receding brightness and leaves a lingering colourful glow. This glorious product is brewed from only the purest water and natural ingredients, and free of artificial additives or preservatives. ", brewery_id: arran.id})
Beer.create!({name: "ID Black IPA", avb: "6%", description: "Originally an American beer style, the Black IPA, also known as a “Cascadian Dark Ale” is a contradiction claiming to be dark and pale in the same title. 
    Arran’s Black IPA combines the colour and roasted malt characteristics of a porter or stout, with the drinkability of a pale ale, the smokiness of a German Black Lager, and the intense hop aroma of an American IPA.", brewery_id: arran.id})
Beer.create!({name: "Arran Dark", avb: "4.3%", description: "There is something of a pagan feel about Arran. A place where nature still holds sway. Where the qualities of tradition are still valued. This Isle of Arran Dark Premium Beer offers you a smooth beer of weight and substance, brewed from only the purest water and natural ingredients, and free of artificial additives or preservatives. ", brewery_id: arran.id})
Beer.create!({name: "Arran Blonde", avb: "5%", description: "Isle of Arran Blonde Premium Beer is a product of its place: an island where nature still holds sway, where tradition is still valued. Arran blonde combines substance with zest, significance with freshness. A truly fine beer brewed from only the purest water and natural ingredients, and free of artificial additives or preservatives. ", brewery_id: arran.id})
Beer.create!({name: "Guid Ale", avb: "3.8%", description: "A light beer that is clean and fresh in flavour but with a significant presence. A truly fine beer brewed from only the purest water and natural ingredients, and free of artificial additives or preservatives. ", brewery_id: arran.id})








# Beer.create!({name: "", avb: "", description: "%", brewery_id: alechemy.id})















